# Generated by Django 4.1.7 on 2023-03-21 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0002_contact_contact_account_con_created_8bdae6_idx'),  # noqa: BLK100
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_form',
            new_name='user_from',
        ),
    ]
