services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - ../data/db:/var/lib/postgresql/data
      - ./scripts/postgres/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    networks:
      - bookmarks
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: my_redis
    networks:
      - bookmarks
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build: .
    volumes:
      - .:/bookmarks
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    networks:
      - bookmarks
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

networks:
  bookmarks:
    driver: bridge

volumes:
  redis_data: